"""Release metadata: what's mirrored, and what each release supports.

Reads a small manifest at s3://scigantic-bindingdb/_MANIFEST.json. Unlike
scigantic-chembl's manifest, this one is not yet regenerated by a cron --
BindingDB releases monthly and re-mirroring here is still a manual step, so
the manifest is hand-published alongside each mirror run. The mechanism is
kept identical to scigantic-chembl's on purpose, so a cron can be added later
without changing this module or anything that calls it.

The manifest is fetched once per process and cached. If it can't be fetched
(no network, a bucket hiccup), calls fall back to the snapshot below rather
than failing outright: worst case is that the package is only as fresh as
this package version, not broken.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
import warnings
from dataclasses import dataclass
from typing import Any, cast

from ._constants import BUCKET, REGION

_MANIFEST_URL = f"https://{BUCKET}.s3.{REGION}.amazonaws.com/_MANIFEST.json"
_TIMEOUT_SECONDS = 5

# Last-known-good snapshot, shipped with this package version. Only used if
# the live manifest can't be fetched.
_FALLBACK_LATEST = "202608"
_FALLBACK_RELEASES = {
    "202608": {"raw": True, "chembl_bridge": True, "dti_pairs": True},
}


class UnknownReleaseError(LookupError):
    """Raised when a release isn't mirrored at all."""


class ReleaseCapabilityError(LookupError):
    """Raised when a release doesn't carry the artifact a call asked for."""


@dataclass(frozen=True)
class ReleaseInfo:
    release: str
    raw: bool
    chembl_bridge: bool
    dti_pairs: bool


_cache: dict[str, Any] | None = None


def _manifest() -> dict[str, Any]:
    global _cache
    if _cache is not None:
        return _cache
    try:
        with urllib.request.urlopen(_MANIFEST_URL, timeout=_TIMEOUT_SECONDS) as response:
            _cache = json.loads(response.read())
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        # HTTPError (a URLError subclass) carries an open response body; left
        # unclosed it raises its own ResourceWarning on garbage collection,
        # on top of the one we're about to emit deliberately below.
        if isinstance(exc, urllib.error.HTTPError):
            exc.close()
        warnings.warn(
            f"could not fetch the live release manifest ({exc!r}); falling back "
            "to the snapshot shipped with this package version, which may be stale",
            stacklevel=3,
        )
        _cache = {"latest": _FALLBACK_LATEST, "releases": _FALLBACK_RELEASES}
    return _cache


def releases() -> list[ReleaseInfo]:
    """List every release the mirror carries, and what each one supports."""
    data = _manifest()
    return [ReleaseInfo(release=name, **caps) for name, caps in data["releases"].items()]


def latest() -> str:
    """The release the archive treats as its current default."""
    return cast(str, _manifest()["latest"])


def _validate_release(release: str) -> None:
    data = _manifest()
    if release not in data["releases"]:
        known = ", ".join(data["releases"])
        raise UnknownReleaseError(f"{release!r} is not mirrored. Known releases: {known}.")


def _require(release: str, capability: str) -> None:
    _validate_release(release)
    data = _manifest()
    if not data["releases"][release][capability]:
        raise ReleaseCapabilityError(
            f"{release!r} has no {capability.replace('_', ' ')}. Call releases() to "
            "see what each release supports, or use query() against the raw "
            "parquet tables instead."
        )
